export const SIGNUP = "SIGNUP"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_ERROR = "SIGNUP_ERROR"

export const SIGNIN = "SIGNIN"
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const SIGNIN_ERROR = "SIGNIN_ERROR"

export const VIEWUSER = "VIEWUSER"
export const VIEWUSER_SUCCESS = "VIEWUSER_SUCCESS"
export const VIEWUSER_ERROR = "VIEWUSER_ERROR"

export const DELETEUSER = "DELETEUSER"
export const DELETEUSER_SUCCESS = "DELETEUSER_SUCCESS"
export const DELETEUSER_ERROR = "DELETEUSER_ERROR"

export const FINEONE_USER = "FINEONE_USER"
export const FINEONE_USER_SUCCESS = "FINEONE_USER_SUCCESS"
export const FINEONE_USER_ERROR = "FINEONE_USER_ERROR"

export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"